### ISSUE TITLE
Unable to connect to NVR

### ISSUE THREAD

**Issue by soffes** [Silvenga/unifi-udm-api-proxy-ha#1]
I tired to add this addon, but I'm getting this error when I start Home Assistant:

```
Logger: custom_components.unifiprotect
Source: custom_components/unifiprotect/__init__.py:122 
First occurred: 9:13:04 PM (1 occurrences) 
Last logged: 9:13:04 PM

Unable to connect to NVR: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //61535f70_unifi-udm-api-proxy:443:7443/api/auth (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff44400fe10>: Failed to establish a new connection: [Errno -3] Try again'))
```

Here is my configuration for the addon:

```yaml
udm:
  uri: "https://10.0.0.1"
```

I can reach the UniFi OS UI for UniFi Protect at https://10.0.0.1/protect/ in my browser. I had the `unifiprotect` custom component working with my CloudKey Gen 2+. I'm really looking forward to getting it setup with my new UDM Pro :)

Thanks for creating this addon!

**Comment by Silvenga** [comment]
Oh, looks the same as https://github.com/Silvenga/unifi-udm-api-proxy/issues/9#issuecomment-602887264 (also contains possible solution). Let me know if that works, or doesn't work. If it doesn't work, please post your redacted unifiprotect config.

I forgot that the `port` option isn't documented by the unifiprotect project - so I can see that being confusing. `unifiprotect` also hardcoded https, so that's not need either. I'll update this project to listen on 7443 by default.

**Comment by Silvenga** [comment]
@soffes I pushed an update, please try and update and make sure your `unifiprotect` config looks something like:

```yaml
unifiprotect: 
  host: 61535f70-unifi-udm-api-proxy
```

**Comment by soffes** [comment]
It's still not working for me. I tried with version `1.5.1` of your add-on. I have version `0.1.3` of `unifiprotect` from HACS. I get the following error:

<img width="647" alt="Screen Shot 2020-03-23 at 8 04 57 PM" src="https://user-images.githubusercontent.com/52870/77384066-b8dcc780-6d41-11ea-90c5-94deffab03ce.png">

Configuration:

```yaml
unifiprotect:
  host: 61535f70-unifi-udm-api-proxy
  username: !secret unifi_protect_username
  password: !secret unifi_protect_password
```

Add-on configuration:

```yaml
udm:
  uri: 'https://10.0.0.1'
```

I also tried with `https://10.0.0.1/`.

Let me know if you need any other information!

**Comment by soffes** [comment]
I forgot to recreate my Home Assistant user in my UDM 🤦‍♂. Version `1.5.1` is working for me! Thank you for creating this add-on! ❤️

**Comment by Silvenga** [comment]
😹 Awesome! My pleasure, thanks for testing it.
